### ISSUE TITLE
Complete README

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby-gets-input#1]
[Outline provided](https://github.com/learn-co-curriculum/ruby-gets-input/blob/master/README.md).

**Comment by aviflombaum** [comment]
Assigning to @SophieDeBenedetto

**Comment by aviflombaum** [comment]
As discussed we're going to turn this back into a README so @SophieDeBenedetto is going to extract the lab that is currently there and write the readme as outlined in https://github.com/learn-co-curriculum/ruby-gets-input/blob/2ae5d553779ad458c22506573e98f1679228daf9/README.md

**Comment by SophieDeBenedetto** [comment]
ready for review

@aviflombaum

**Comment by aviflombaum** [comment]
reviewing now

**Comment by aviflombaum** [comment]
Reviewed: https://github.com/learn-co-curriculum/ruby-gets-input/commit/c17069b14a6b871475421b8852126a13719e666f
