### ISSUE TITLE
Code Along Instructions Still Confusing

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby-gets-input#13]
We have to figure out a better format for READMEs where the intention is for the student to follow along. A part of me thinks why not turn it into an optional lab? We should discuss.

cc @jmburges @matbalez @AnnJohn 

This is definitely a product thing on Learn and not specific to this lesson but I feel like the code along instructions in this one are particularly ruff. 

Mat, once we bring this into product, let's close out this issue.

<3

**Comment by AnnJohn** [comment]
made this a lab where the tests automatically pass when run so that students can still see the file structure the lesson is explaining
