### ISSUE TITLE
"Gets CLI input" & "Greetng CLI Lab" sections really confusing

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/ruby-gets-input#16]
A fellow student suggested I post this here--I've been chugging along nicely till I got to these sections. All of a sudden I found myself lost. To me, there are a few huge gaps in the lesson. For example, the instruction seems to clearly suggest "write code in the file in the /lib" -- but, as I have discovered, the file in /bin also needs to be modified.

In addition, it is not clear at all what the exact wording the program expects. If one needs to copy from the spec file, why not say so? Instead, the instructions suggest some generic "greeting".

Now if I totally missed something--which in entirely possible, I'd love to know. So far I've been enjoying the labs.

**Comment by AnnJohn** [comment]
Hi @CodeByLine this lesson is a Readme so there isn't anything that's expected of the student, but it looks like you're having issues with two other labs in this track. Could you post your specific questions and issues regarding those labs in the repositories where they're located. That way, we can better address the specific problems/gaps. Tahnks.

**Comment by CodeByLine** [comment]
Sorry--wasn't aware of your response. I have since resolved those questions. Thank you though!
