### ISSUE TITLE
Numbered list continuation

### ISSUE THREAD

**Issue by Eearslya** [learn-co-curriculum/ruby-gets-input#24]
![image](https://cloud.githubusercontent.com/assets/2270586/22043487/a494877e-dcc4-11e6-9996-40bc4229d218.png)

This may be an issue with the site's Markdown interpreter itself, but you can see in this lesson that the numbered list from the top of the `README` file gets continued here, a couple paragraphs down.

Worth noting that this issue does not appear when viewed on GitHub itself.

**Comment by gj** [comment]
Fixed in 9cf17ea.

Thanks @Eearslya !
